/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *lbSttMsg;
    QPushButton *btnStart;
    QGroupBox *groupBox;
    QTabWidget *tabWidget;
    QWidget *tab;
    QPushButton *btnSVOFF;
    QPushButton *btnSVON;
    QGroupBox *groupBox_3;
    QPushButton *btnSpeed_low;
    QPushButton *btnSpeed_med;
    QPushButton *btnSpeed_high;
    QPushButton *btnSpeed_top;
    QGroupBox *groupBox_4;
    QPushButton *btnJ2_neg;
    QPushButton *btnJ4_neg;
    QPushButton *btnJ3_neg;
    QPushButton *btnJ1_pos;
    QPushButton *btnJ1_neg;
    QPushButton *btnJ2_pos;
    QPushButton *btnJ3_pos;
    QPushButton *btnJ4_pos;
    QPushButton *btnJ5_pos;
    QPushButton *btnJ5_neg;
    QPushButton *btnJ6_pos;
    QPushButton *btnJ6_neg;
    QComboBox *chbCoords;
    QComboBox *chbTools;
    QLabel *label_42;
    QLabel *label_43;
    QWidget *tab_2;
    QPushButton *btnSendProg;
    QPushButton *btnWriteProg;
    QPushButton *btnCompProg;
    QLabel *label_28;
    QLineEdit *lnEProgName;
    QPushButton *btnSendPoints;
    QPushButton *btnChPoints;
    QWidget *tab_7;
    QPushButton *btnDataAdd;
    QPushButton *btnDataReteach;
    QPushButton *btnDataMove;
    QPushButton *btnDataDel;
    QTabWidget *tabWidget_3;
    QWidget *tab_8;
    QTableWidget *tabJPointList_1;
    QTableWidget *tabJPointList_2;
    QTableWidget *tabJPointList_3;
    QTableWidget *tabJPointList_4;
    QWidget *tab_9;
    QTableWidget *tabWPointList_1;
    QTableWidget *tabWPointList_2;
    QTableWidget *tabWPointList_3;
    QTableWidget *tabWPointList_4;
    QLabel *label_39;
    QComboBox *comboBox;
    QGroupBox *groupBox_2;
    QTabWidget *tabWidget_2;
    QWidget *tab_3;
    QLabel *label_10;
    QLabel *label_15;
    QLabel *label_8;
    QLineEdit *lnERecv_theta2;
    QLineEdit *lnERecv_z;
    QLabel *label_14;
    QLineEdit *lnERecv_x;
    QLineEdit *lnERecv_roll;
    QLineEdit *lnERecv_d3;
    QLineEdit *lnERecv_pitch;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_7;
    QLabel *label_16;
    QLineEdit *lnERecv_theta4;
    QLineEdit *lnERecv_y;
    QLineEdit *lnERecv_theta1;
    QLabel *label_9;
    QLineEdit *lnERecv_yaw;
    QLabel *label_11;
    QLabel *label;
    QLineEdit *lnECmd;
    QGroupBox *groupBox_5;
    QLabel *label_3;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_40;
    QLabel *label_41;
    QLineEdit *lnE_ToolNum1;
    QLineEdit *lnE_JogSp1;
    QLineEdit *lnE_Coord1;
    QLineEdit *lnE_ServoStt1;
    QLineEdit *lnE_SysStt1;
    QLabel *label_64;
    QLabel *label_65;
    QLineEdit *lnE_SysStt1_2;
    QLineEdit *lnE_SysStt1_3;
    QWidget *tab_4;
    QLabel *label_17;
    QLineEdit *lnERecv_theta1_1;
    QLabel *label_19;
    QLineEdit *lnECmd1;
    QLineEdit *lnERecv_roll1;
    QLabel *label_20;
    QLineEdit *lnERecv_y1;
    QLabel *label_21;
    QLineEdit *lnERecv_theta3_1;
    QLineEdit *lnERecv_x1;
    QLineEdit *lnERecv_pitch1;
    QLabel *label_22;
    QLineEdit *lnERecv_z1;
    QLineEdit *lnERecv_yaw1;
    QLabel *label_23;
    QLineEdit *lnERecv_theta2_1;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QGroupBox *groupBox_6;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLineEdit *lnE_ToolNum2;
    QLineEdit *lnE_JogSp2;
    QLineEdit *lnE_Coord2;
    QLineEdit *lnE_ServoStt2;
    QLineEdit *lnE_SysStt2;
    QLabel *label_66;
    QLabel *label_67;
    QLineEdit *lnE_SysStt1_4;
    QLineEdit *lnE_SysStt1_5;
    QWidget *tab_6;
    QLineEdit *lnERecv_y2;
    QLineEdit *lnERecv_yaw2;
    QLabel *label_29;
    QLineEdit *lnERecv_theta2_2;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLineEdit *lnECmd2;
    QLineEdit *lnERecv_theta3_2;
    QLineEdit *lnERecv_roll2;
    QLineEdit *lnERecv_x2;
    QLineEdit *lnERecv_pitch2;
    QLineEdit *lnERecv_theta1_2;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *lnERecv_z2;
    QLabel *label_37;
    QLabel *label_38;
    QGroupBox *groupBox_7;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLineEdit *lnE_ToolNum3;
    QLineEdit *lnE_JogSp3;
    QLineEdit *lnE_Coord3;
    QLineEdit *lnE_ServoStt3;
    QLineEdit *lnE_SysStt3;
    QLabel *label_68;
    QLabel *label_69;
    QLineEdit *lnE_SysStt1_6;
    QLineEdit *lnE_SysStt1_7;
    QWidget *tab_5;
    QLabel *label_92;
    QLineEdit *lnERecv_y3;
    QLabel *label_93;
    QLabel *label_94;
    QLineEdit *lnERecv_roll3;
    QLabel *label_95;
    QLabel *label_96;
    QLineEdit *lnERecv_yaw3;
    QLineEdit *lnERecv_J4;
    QLineEdit *lnERecv_z3;
    QLineEdit *lnERecv_pitch3;
    QLabel *label_97;
    QLineEdit *lnERecv_J1;
    QLineEdit *lnERecv_J3;
    QLabel *label_98;
    QLineEdit *lnERecv_J2;
    QLineEdit *lnECmd3;
    QLineEdit *lnERecv_x3;
    QLabel *label_99;
    QLabel *label_100;
    QLabel *label_101;
    QLabel *label_102;
    QLineEdit *lnERecv_J5;
    QLabel *label_103;
    QLineEdit *lnERecv_J6;
    QLabel *label_104;
    QGroupBox *groupBox_8;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QLabel *label_62;
    QLabel *label_63;
    QLineEdit *lnE_ToolNum4;
    QLineEdit *lnE_JogSp4;
    QLineEdit *lnE_Coord;
    QLineEdit *lnE_ServoStt4;
    QLineEdit *lnE_SysStt4;
    QLabel *label_70;
    QLabel *label_71;
    QLineEdit *lnE_SysStt1_8;
    QLineEdit *lnE_SysStt1_9;
    QLabel *label_2;
    QLineEdit *lnETime;
    QPushButton *btnStop;
    QLabel *label_18;
    QLineEdit *lnENoclients;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1581, 954);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        lbSttMsg = new QLabel(centralwidget);
        lbSttMsg->setObjectName(QString::fromUtf8("lbSttMsg"));
        lbSttMsg->setGeometry(QRect(20, 20, 331, 20));
        btnStart = new QPushButton(centralwidget);
        btnStart->setObjectName(QString::fromUtf8("btnStart"));
        btnStart->setGeometry(QRect(860, 20, 93, 29));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 100, 971, 801));
        groupBox->setAlignment(Qt::AlignCenter);
        tabWidget = new QTabWidget(groupBox);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(20, 100, 951, 691));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        btnSVOFF = new QPushButton(tab);
        btnSVOFF->setObjectName(QString::fromUtf8("btnSVOFF"));
        btnSVOFF->setGeometry(QRect(130, 30, 93, 29));
        btnSVON = new QPushButton(tab);
        btnSVON->setObjectName(QString::fromUtf8("btnSVON"));
        btnSVON->setGeometry(QRect(20, 30, 93, 29));
        groupBox_3 = new QGroupBox(tab);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(570, 10, 131, 191));
        groupBox_3->setAlignment(Qt::AlignCenter);
        btnSpeed_low = new QPushButton(groupBox_3);
        btnSpeed_low->setObjectName(QString::fromUtf8("btnSpeed_low"));
        btnSpeed_low->setGeometry(QRect(20, 30, 93, 29));
        btnSpeed_med = new QPushButton(groupBox_3);
        btnSpeed_med->setObjectName(QString::fromUtf8("btnSpeed_med"));
        btnSpeed_med->setGeometry(QRect(20, 70, 93, 29));
        btnSpeed_high = new QPushButton(groupBox_3);
        btnSpeed_high->setObjectName(QString::fromUtf8("btnSpeed_high"));
        btnSpeed_high->setGeometry(QRect(20, 110, 93, 29));
        btnSpeed_top = new QPushButton(groupBox_3);
        btnSpeed_top->setObjectName(QString::fromUtf8("btnSpeed_top"));
        btnSpeed_top->setGeometry(QRect(20, 150, 93, 29));
        groupBox_4 = new QGroupBox(tab);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(290, 180, 251, 311));
        groupBox_4->setAlignment(Qt::AlignCenter);
        btnJ2_neg = new QPushButton(groupBox_4);
        btnJ2_neg->setObjectName(QString::fromUtf8("btnJ2_neg"));
        btnJ2_neg->setGeometry(QRect(20, 70, 93, 29));
        btnJ4_neg = new QPushButton(groupBox_4);
        btnJ4_neg->setObjectName(QString::fromUtf8("btnJ4_neg"));
        btnJ4_neg->setGeometry(QRect(20, 170, 93, 29));
        btnJ3_neg = new QPushButton(groupBox_4);
        btnJ3_neg->setObjectName(QString::fromUtf8("btnJ3_neg"));
        btnJ3_neg->setGeometry(QRect(20, 120, 93, 29));
        btnJ1_pos = new QPushButton(groupBox_4);
        btnJ1_pos->setObjectName(QString::fromUtf8("btnJ1_pos"));
        btnJ1_pos->setGeometry(QRect(130, 20, 93, 29));
        btnJ1_neg = new QPushButton(groupBox_4);
        btnJ1_neg->setObjectName(QString::fromUtf8("btnJ1_neg"));
        btnJ1_neg->setGeometry(QRect(20, 20, 93, 29));
        btnJ2_pos = new QPushButton(groupBox_4);
        btnJ2_pos->setObjectName(QString::fromUtf8("btnJ2_pos"));
        btnJ2_pos->setGeometry(QRect(130, 70, 93, 29));
        btnJ3_pos = new QPushButton(groupBox_4);
        btnJ3_pos->setObjectName(QString::fromUtf8("btnJ3_pos"));
        btnJ3_pos->setGeometry(QRect(130, 120, 93, 29));
        btnJ4_pos = new QPushButton(groupBox_4);
        btnJ4_pos->setObjectName(QString::fromUtf8("btnJ4_pos"));
        btnJ4_pos->setGeometry(QRect(130, 170, 93, 29));
        btnJ5_pos = new QPushButton(groupBox_4);
        btnJ5_pos->setObjectName(QString::fromUtf8("btnJ5_pos"));
        btnJ5_pos->setGeometry(QRect(130, 220, 93, 29));
        btnJ5_neg = new QPushButton(groupBox_4);
        btnJ5_neg->setObjectName(QString::fromUtf8("btnJ5_neg"));
        btnJ5_neg->setGeometry(QRect(20, 220, 93, 29));
        btnJ6_pos = new QPushButton(groupBox_4);
        btnJ6_pos->setObjectName(QString::fromUtf8("btnJ6_pos"));
        btnJ6_pos->setGeometry(QRect(130, 270, 93, 29));
        btnJ6_neg = new QPushButton(groupBox_4);
        btnJ6_neg->setObjectName(QString::fromUtf8("btnJ6_neg"));
        btnJ6_neg->setGeometry(QRect(20, 270, 93, 29));
        chbCoords = new QComboBox(tab);
        chbCoords->addItem(QString());
        chbCoords->addItem(QString());
        chbCoords->addItem(QString());
        chbCoords->addItem(QString());
        chbCoords->addItem(QString());
        chbCoords->setObjectName(QString::fromUtf8("chbCoords"));
        chbCoords->setGeometry(QRect(350, 80, 191, 26));
        chbTools = new QComboBox(tab);
        chbTools->addItem(QString());
        chbTools->setObjectName(QString::fromUtf8("chbTools"));
        chbTools->setGeometry(QRect(350, 120, 191, 26));
        label_42 = new QLabel(tab);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(260, 80, 81, 20));
        label_43 = new QLabel(tab);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(260, 120, 63, 20));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        btnSendProg = new QPushButton(tab_2);
        btnSendProg->setObjectName(QString::fromUtf8("btnSendProg"));
        btnSendProg->setGeometry(QRect(540, 470, 131, 41));
        btnWriteProg = new QPushButton(tab_2);
        btnWriteProg->setObjectName(QString::fromUtf8("btnWriteProg"));
        btnWriteProg->setGeometry(QRect(30, 470, 131, 41));
        btnCompProg = new QPushButton(tab_2);
        btnCompProg->setObjectName(QString::fromUtf8("btnCompProg"));
        btnCompProg->setGeometry(QRect(280, 470, 151, 41));
        label_28 = new QLabel(tab_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(20, 50, 121, 20));
        lnEProgName = new QLineEdit(tab_2);
        lnEProgName->setObjectName(QString::fromUtf8("lnEProgName"));
        lnEProgName->setGeometry(QRect(170, 50, 191, 26));
        btnSendPoints = new QPushButton(tab_2);
        btnSendPoints->setObjectName(QString::fromUtf8("btnSendPoints"));
        btnSendPoints->setGeometry(QRect(270, 400, 161, 41));
        btnChPoints = new QPushButton(tab_2);
        btnChPoints->setObjectName(QString::fromUtf8("btnChPoints"));
        btnChPoints->setGeometry(QRect(30, 400, 161, 41));
        tabWidget->addTab(tab_2, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        btnDataAdd = new QPushButton(tab_7);
        btnDataAdd->setObjectName(QString::fromUtf8("btnDataAdd"));
        btnDataAdd->setGeometry(QRect(390, 600, 93, 29));
        btnDataReteach = new QPushButton(tab_7);
        btnDataReteach->setObjectName(QString::fromUtf8("btnDataReteach"));
        btnDataReteach->setGeometry(QRect(510, 600, 93, 29));
        btnDataMove = new QPushButton(tab_7);
        btnDataMove->setObjectName(QString::fromUtf8("btnDataMove"));
        btnDataMove->setGeometry(QRect(630, 600, 93, 29));
        btnDataDel = new QPushButton(tab_7);
        btnDataDel->setObjectName(QString::fromUtf8("btnDataDel"));
        btnDataDel->setGeometry(QRect(750, 600, 93, 29));
        tabWidget_3 = new QTabWidget(tab_7);
        tabWidget_3->setObjectName(QString::fromUtf8("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(10, 100, 931, 501));
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        tabJPointList_1 = new QTableWidget(tab_8);
        if (tabJPointList_1->columnCount() < 7)
            tabJPointList_1->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tabJPointList_1->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tabJPointList_1->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tabJPointList_1->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tabJPointList_1->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tabJPointList_1->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tabJPointList_1->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tabJPointList_1->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        if (tabJPointList_1->rowCount() < 20)
            tabJPointList_1->setRowCount(20);
        tabJPointList_1->setObjectName(QString::fromUtf8("tabJPointList_1"));
        tabJPointList_1->setGeometry(QRect(10, 10, 911, 441));
        tabJPointList_1->setLineWidth(1);
        tabJPointList_1->setRowCount(20);
        tabJPointList_1->verticalHeader()->setVisible(false);
        tabJPointList_2 = new QTableWidget(tab_8);
        if (tabJPointList_2->columnCount() < 7)
            tabJPointList_2->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tabJPointList_2->setHorizontalHeaderItem(0, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tabJPointList_2->setHorizontalHeaderItem(1, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tabJPointList_2->setHorizontalHeaderItem(2, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tabJPointList_2->setHorizontalHeaderItem(3, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tabJPointList_2->setHorizontalHeaderItem(4, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tabJPointList_2->setHorizontalHeaderItem(5, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tabJPointList_2->setHorizontalHeaderItem(6, __qtablewidgetitem13);
        if (tabJPointList_2->rowCount() < 20)
            tabJPointList_2->setRowCount(20);
        tabJPointList_2->setObjectName(QString::fromUtf8("tabJPointList_2"));
        tabJPointList_2->setGeometry(QRect(10, 10, 911, 441));
        tabJPointList_2->setLineWidth(1);
        tabJPointList_2->setRowCount(20);
        tabJPointList_2->verticalHeader()->setVisible(false);
        tabJPointList_3 = new QTableWidget(tab_8);
        if (tabJPointList_3->columnCount() < 7)
            tabJPointList_3->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tabJPointList_3->setHorizontalHeaderItem(0, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tabJPointList_3->setHorizontalHeaderItem(1, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tabJPointList_3->setHorizontalHeaderItem(2, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tabJPointList_3->setHorizontalHeaderItem(3, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tabJPointList_3->setHorizontalHeaderItem(4, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tabJPointList_3->setHorizontalHeaderItem(5, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tabJPointList_3->setHorizontalHeaderItem(6, __qtablewidgetitem20);
        if (tabJPointList_3->rowCount() < 20)
            tabJPointList_3->setRowCount(20);
        tabJPointList_3->setObjectName(QString::fromUtf8("tabJPointList_3"));
        tabJPointList_3->setGeometry(QRect(10, 10, 911, 441));
        tabJPointList_3->setLineWidth(1);
        tabJPointList_3->setRowCount(20);
        tabJPointList_3->verticalHeader()->setVisible(false);
        tabJPointList_4 = new QTableWidget(tab_8);
        if (tabJPointList_4->columnCount() < 7)
            tabJPointList_4->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tabJPointList_4->setHorizontalHeaderItem(0, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tabJPointList_4->setHorizontalHeaderItem(1, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tabJPointList_4->setHorizontalHeaderItem(2, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tabJPointList_4->setHorizontalHeaderItem(3, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tabJPointList_4->setHorizontalHeaderItem(4, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tabJPointList_4->setHorizontalHeaderItem(5, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tabJPointList_4->setHorizontalHeaderItem(6, __qtablewidgetitem27);
        if (tabJPointList_4->rowCount() < 20)
            tabJPointList_4->setRowCount(20);
        tabJPointList_4->setObjectName(QString::fromUtf8("tabJPointList_4"));
        tabJPointList_4->setGeometry(QRect(10, 10, 911, 441));
        tabJPointList_4->setLineWidth(1);
        tabJPointList_4->setRowCount(20);
        tabJPointList_4->verticalHeader()->setVisible(false);
        tabWidget_3->addTab(tab_8, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QString::fromUtf8("tab_9"));
        tabWPointList_1 = new QTableWidget(tab_9);
        if (tabWPointList_1->columnCount() < 7)
            tabWPointList_1->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tabWPointList_1->setHorizontalHeaderItem(0, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tabWPointList_1->setHorizontalHeaderItem(1, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tabWPointList_1->setHorizontalHeaderItem(2, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tabWPointList_1->setHorizontalHeaderItem(3, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tabWPointList_1->setHorizontalHeaderItem(4, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tabWPointList_1->setHorizontalHeaderItem(5, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tabWPointList_1->setHorizontalHeaderItem(6, __qtablewidgetitem34);
        if (tabWPointList_1->rowCount() < 20)
            tabWPointList_1->setRowCount(20);
        tabWPointList_1->setObjectName(QString::fromUtf8("tabWPointList_1"));
        tabWPointList_1->setGeometry(QRect(10, 20, 911, 441));
        tabWPointList_1->setRowCount(20);
        tabWPointList_1->verticalHeader()->setVisible(false);
        tabWPointList_1->verticalHeader()->setHighlightSections(true);
        tabWPointList_2 = new QTableWidget(tab_9);
        if (tabWPointList_2->columnCount() < 7)
            tabWPointList_2->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tabWPointList_2->setHorizontalHeaderItem(0, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tabWPointList_2->setHorizontalHeaderItem(1, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tabWPointList_2->setHorizontalHeaderItem(2, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tabWPointList_2->setHorizontalHeaderItem(3, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tabWPointList_2->setHorizontalHeaderItem(4, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tabWPointList_2->setHorizontalHeaderItem(5, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tabWPointList_2->setHorizontalHeaderItem(6, __qtablewidgetitem41);
        if (tabWPointList_2->rowCount() < 20)
            tabWPointList_2->setRowCount(20);
        tabWPointList_2->setObjectName(QString::fromUtf8("tabWPointList_2"));
        tabWPointList_2->setGeometry(QRect(10, 20, 911, 441));
        tabWPointList_2->setRowCount(20);
        tabWPointList_2->verticalHeader()->setVisible(false);
        tabWPointList_2->verticalHeader()->setHighlightSections(true);
        tabWPointList_3 = new QTableWidget(tab_9);
        if (tabWPointList_3->columnCount() < 7)
            tabWPointList_3->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tabWPointList_3->setHorizontalHeaderItem(0, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tabWPointList_3->setHorizontalHeaderItem(1, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tabWPointList_3->setHorizontalHeaderItem(2, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tabWPointList_3->setHorizontalHeaderItem(3, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tabWPointList_3->setHorizontalHeaderItem(4, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tabWPointList_3->setHorizontalHeaderItem(5, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tabWPointList_3->setHorizontalHeaderItem(6, __qtablewidgetitem48);
        if (tabWPointList_3->rowCount() < 20)
            tabWPointList_3->setRowCount(20);
        tabWPointList_3->setObjectName(QString::fromUtf8("tabWPointList_3"));
        tabWPointList_3->setGeometry(QRect(10, 20, 911, 441));
        tabWPointList_3->setRowCount(20);
        tabWPointList_3->verticalHeader()->setVisible(false);
        tabWPointList_3->verticalHeader()->setHighlightSections(true);
        tabWPointList_4 = new QTableWidget(tab_9);
        if (tabWPointList_4->columnCount() < 7)
            tabWPointList_4->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        tabWPointList_4->setHorizontalHeaderItem(0, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        tabWPointList_4->setHorizontalHeaderItem(1, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        tabWPointList_4->setHorizontalHeaderItem(2, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tabWPointList_4->setHorizontalHeaderItem(3, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tabWPointList_4->setHorizontalHeaderItem(4, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tabWPointList_4->setHorizontalHeaderItem(5, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tabWPointList_4->setHorizontalHeaderItem(6, __qtablewidgetitem55);
        if (tabWPointList_4->rowCount() < 20)
            tabWPointList_4->setRowCount(20);
        tabWPointList_4->setObjectName(QString::fromUtf8("tabWPointList_4"));
        tabWPointList_4->setGeometry(QRect(10, 20, 911, 441));
        tabWPointList_4->setRowCount(20);
        tabWPointList_4->verticalHeader()->setVisible(false);
        tabWPointList_4->verticalHeader()->setHighlightSections(true);
        tabWidget_3->addTab(tab_9, QString());
        tabWidget->addTab(tab_7, QString());
        label_39 = new QLabel(groupBox);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(10, 50, 63, 20));
        comboBox = new QComboBox(groupBox);
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(100, 50, 191, 26));
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(1030, 100, 531, 791));
        groupBox_2->setAlignment(Qt::AlignCenter);
        tabWidget_2 = new QTabWidget(groupBox_2);
        tabWidget_2->setObjectName(QString::fromUtf8("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(10, 40, 511, 741));
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        label_10 = new QLabel(tab_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(30, 490, 41, 20));
        label_15 = new QLabel(tab_3);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(290, 440, 63, 20));
        label_8 = new QLabel(tab_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(30, 390, 21, 20));
        lnERecv_theta2 = new QLineEdit(tab_3);
        lnERecv_theta2->setObjectName(QString::fromUtf8("lnERecv_theta2"));
        lnERecv_theta2->setGeometry(QRect(372, 385, 111, 31));
        lnERecv_z = new QLineEdit(tab_3);
        lnERecv_z->setObjectName(QString::fromUtf8("lnERecv_z"));
        lnERecv_z->setGeometry(QRect(110, 440, 113, 26));
        label_14 = new QLabel(tab_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(290, 340, 63, 20));
        lnERecv_x = new QLineEdit(tab_3);
        lnERecv_x->setObjectName(QString::fromUtf8("lnERecv_x"));
        lnERecv_x->setGeometry(QRect(110, 340, 113, 26));
        lnERecv_roll = new QLineEdit(tab_3);
        lnERecv_roll->setObjectName(QString::fromUtf8("lnERecv_roll"));
        lnERecv_roll->setGeometry(QRect(110, 490, 113, 26));
        lnERecv_d3 = new QLineEdit(tab_3);
        lnERecv_d3->setObjectName(QString::fromUtf8("lnERecv_d3"));
        lnERecv_d3->setGeometry(QRect(372, 435, 111, 31));
        lnERecv_pitch = new QLineEdit(tab_3);
        lnERecv_pitch->setObjectName(QString::fromUtf8("lnERecv_pitch"));
        lnERecv_pitch->setGeometry(QRect(110, 540, 113, 26));
        label_12 = new QLabel(tab_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(30, 590, 63, 20));
        label_13 = new QLabel(tab_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(290, 390, 63, 20));
        label_7 = new QLabel(tab_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(30, 340, 31, 20));
        label_16 = new QLabel(tab_3);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(290, 490, 63, 20));
        lnERecv_theta4 = new QLineEdit(tab_3);
        lnERecv_theta4->setObjectName(QString::fromUtf8("lnERecv_theta4"));
        lnERecv_theta4->setGeometry(QRect(370, 480, 111, 31));
        lnERecv_y = new QLineEdit(tab_3);
        lnERecv_y->setObjectName(QString::fromUtf8("lnERecv_y"));
        lnERecv_y->setGeometry(QRect(110, 390, 113, 26));
        lnERecv_theta1 = new QLineEdit(tab_3);
        lnERecv_theta1->setObjectName(QString::fromUtf8("lnERecv_theta1"));
        lnERecv_theta1->setGeometry(QRect(372, 340, 111, 31));
        label_9 = new QLabel(tab_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(30, 440, 31, 20));
        lnERecv_yaw = new QLineEdit(tab_3);
        lnERecv_yaw->setObjectName(QString::fromUtf8("lnERecv_yaw"));
        lnERecv_yaw->setGeometry(QRect(110, 590, 113, 26));
        label_11 = new QLabel(tab_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(30, 540, 51, 20));
        label = new QLabel(tab_3);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 650, 81, 20));
        lnECmd = new QLineEdit(tab_3);
        lnECmd->setObjectName(QString::fromUtf8("lnECmd"));
        lnECmd->setGeometry(QRect(110, 650, 381, 26));
        groupBox_5 = new QGroupBox(tab_3);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(20, 10, 451, 301));
        groupBox_5->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(groupBox_5);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 30, 101, 20));
        label_5 = new QLabel(groupBox_5);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 70, 111, 20));
        label_6 = new QLabel(groupBox_5);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 180, 101, 20));
        label_40 = new QLabel(groupBox_5);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 140, 101, 20));
        label_41 = new QLabel(groupBox_5);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 110, 201, 20));
        lnE_ToolNum1 = new QLineEdit(groupBox_5);
        lnE_ToolNum1->setObjectName(QString::fromUtf8("lnE_ToolNum1"));
        lnE_ToolNum1->setGeometry(QRect(130, 30, 113, 26));
        lnE_JogSp1 = new QLineEdit(groupBox_5);
        lnE_JogSp1->setObjectName(QString::fromUtf8("lnE_JogSp1"));
        lnE_JogSp1->setGeometry(QRect(130, 70, 211, 26));
        lnE_Coord1 = new QLineEdit(groupBox_5);
        lnE_Coord1->setObjectName(QString::fromUtf8("lnE_Coord1"));
        lnE_Coord1->setGeometry(QRect(220, 100, 211, 26));
        lnE_ServoStt1 = new QLineEdit(groupBox_5);
        lnE_ServoStt1->setObjectName(QString::fromUtf8("lnE_ServoStt1"));
        lnE_ServoStt1->setGeometry(QRect(130, 140, 211, 26));
        lnE_SysStt1 = new QLineEdit(groupBox_5);
        lnE_SysStt1->setObjectName(QString::fromUtf8("lnE_SysStt1"));
        lnE_SysStt1->setGeometry(QRect(130, 180, 211, 26));
        label_64 = new QLabel(groupBox_5);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(10, 220, 63, 20));
        label_65 = new QLabel(groupBox_5);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(10, 260, 101, 20));
        lnE_SysStt1_2 = new QLineEdit(groupBox_5);
        lnE_SysStt1_2->setObjectName(QString::fromUtf8("lnE_SysStt1_2"));
        lnE_SysStt1_2->setGeometry(QRect(130, 220, 211, 26));
        lnE_SysStt1_3 = new QLineEdit(groupBox_5);
        lnE_SysStt1_3->setObjectName(QString::fromUtf8("lnE_SysStt1_3"));
        lnE_SysStt1_3->setGeometry(QRect(130, 260, 211, 26));
        tabWidget_2->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        label_17 = new QLabel(tab_4);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(30, 360, 31, 20));
        lnERecv_theta1_1 = new QLineEdit(tab_4);
        lnERecv_theta1_1->setObjectName(QString::fromUtf8("lnERecv_theta1_1"));
        lnERecv_theta1_1->setGeometry(QRect(370, 360, 111, 31));
        label_19 = new QLabel(tab_4);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(290, 370, 63, 20));
        lnECmd1 = new QLineEdit(tab_4);
        lnECmd1->setObjectName(QString::fromUtf8("lnECmd1"));
        lnECmd1->setGeometry(QRect(110, 670, 381, 26));
        lnERecv_roll1 = new QLineEdit(tab_4);
        lnERecv_roll1->setObjectName(QString::fromUtf8("lnERecv_roll1"));
        lnERecv_roll1->setGeometry(QRect(110, 510, 113, 26));
        label_20 = new QLabel(tab_4);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(30, 560, 51, 20));
        lnERecv_y1 = new QLineEdit(tab_4);
        lnERecv_y1->setObjectName(QString::fromUtf8("lnERecv_y1"));
        lnERecv_y1->setGeometry(QRect(110, 410, 113, 26));
        label_21 = new QLabel(tab_4);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(30, 510, 41, 20));
        lnERecv_theta3_1 = new QLineEdit(tab_4);
        lnERecv_theta3_1->setObjectName(QString::fromUtf8("lnERecv_theta3_1"));
        lnERecv_theta3_1->setGeometry(QRect(370, 460, 111, 31));
        lnERecv_x1 = new QLineEdit(tab_4);
        lnERecv_x1->setObjectName(QString::fromUtf8("lnERecv_x1"));
        lnERecv_x1->setGeometry(QRect(110, 360, 113, 26));
        lnERecv_pitch1 = new QLineEdit(tab_4);
        lnERecv_pitch1->setObjectName(QString::fromUtf8("lnERecv_pitch1"));
        lnERecv_pitch1->setGeometry(QRect(110, 560, 113, 26));
        label_22 = new QLabel(tab_4);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(30, 610, 63, 20));
        lnERecv_z1 = new QLineEdit(tab_4);
        lnERecv_z1->setObjectName(QString::fromUtf8("lnERecv_z1"));
        lnERecv_z1->setGeometry(QRect(110, 460, 113, 26));
        lnERecv_yaw1 = new QLineEdit(tab_4);
        lnERecv_yaw1->setObjectName(QString::fromUtf8("lnERecv_yaw1"));
        lnERecv_yaw1->setGeometry(QRect(110, 610, 113, 26));
        label_23 = new QLabel(tab_4);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(290, 470, 63, 20));
        lnERecv_theta2_1 = new QLineEdit(tab_4);
        lnERecv_theta2_1->setObjectName(QString::fromUtf8("lnERecv_theta2_1"));
        lnERecv_theta2_1->setGeometry(QRect(370, 410, 111, 31));
        label_24 = new QLabel(tab_4);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(30, 410, 21, 20));
        label_25 = new QLabel(tab_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(20, 670, 81, 20));
        label_26 = new QLabel(tab_4);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(30, 460, 31, 20));
        label_27 = new QLabel(tab_4);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(290, 420, 63, 20));
        groupBox_6 = new QGroupBox(tab_4);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(20, 20, 451, 311));
        groupBox_6->setAlignment(Qt::AlignCenter);
        label_49 = new QLabel(groupBox_6);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(10, 30, 101, 20));
        label_50 = new QLabel(groupBox_6);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(10, 70, 111, 20));
        label_51 = new QLabel(groupBox_6);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 180, 101, 20));
        label_52 = new QLabel(groupBox_6);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(10, 140, 101, 20));
        label_53 = new QLabel(groupBox_6);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(10, 110, 201, 20));
        lnE_ToolNum2 = new QLineEdit(groupBox_6);
        lnE_ToolNum2->setObjectName(QString::fromUtf8("lnE_ToolNum2"));
        lnE_ToolNum2->setGeometry(QRect(130, 30, 113, 26));
        lnE_JogSp2 = new QLineEdit(groupBox_6);
        lnE_JogSp2->setObjectName(QString::fromUtf8("lnE_JogSp2"));
        lnE_JogSp2->setGeometry(QRect(130, 70, 211, 26));
        lnE_Coord2 = new QLineEdit(groupBox_6);
        lnE_Coord2->setObjectName(QString::fromUtf8("lnE_Coord2"));
        lnE_Coord2->setGeometry(QRect(220, 100, 211, 26));
        lnE_ServoStt2 = new QLineEdit(groupBox_6);
        lnE_ServoStt2->setObjectName(QString::fromUtf8("lnE_ServoStt2"));
        lnE_ServoStt2->setGeometry(QRect(130, 140, 211, 26));
        lnE_SysStt2 = new QLineEdit(groupBox_6);
        lnE_SysStt2->setObjectName(QString::fromUtf8("lnE_SysStt2"));
        lnE_SysStt2->setGeometry(QRect(130, 180, 211, 26));
        label_66 = new QLabel(groupBox_6);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(10, 260, 101, 20));
        label_67 = new QLabel(groupBox_6);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(10, 220, 63, 20));
        lnE_SysStt1_4 = new QLineEdit(groupBox_6);
        lnE_SysStt1_4->setObjectName(QString::fromUtf8("lnE_SysStt1_4"));
        lnE_SysStt1_4->setGeometry(QRect(130, 260, 211, 26));
        lnE_SysStt1_5 = new QLineEdit(groupBox_6);
        lnE_SysStt1_5->setObjectName(QString::fromUtf8("lnE_SysStt1_5"));
        lnE_SysStt1_5->setGeometry(QRect(130, 220, 211, 26));
        tabWidget_2->addTab(tab_4, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        lnERecv_y2 = new QLineEdit(tab_6);
        lnERecv_y2->setObjectName(QString::fromUtf8("lnERecv_y2"));
        lnERecv_y2->setGeometry(QRect(110, 410, 113, 26));
        lnERecv_yaw2 = new QLineEdit(tab_6);
        lnERecv_yaw2->setObjectName(QString::fromUtf8("lnERecv_yaw2"));
        lnERecv_yaw2->setGeometry(QRect(110, 610, 113, 26));
        label_29 = new QLabel(tab_6);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(20, 670, 81, 20));
        lnERecv_theta2_2 = new QLineEdit(tab_6);
        lnERecv_theta2_2->setObjectName(QString::fromUtf8("lnERecv_theta2_2"));
        lnERecv_theta2_2->setGeometry(QRect(350, 400, 111, 31));
        label_30 = new QLabel(tab_6);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(30, 610, 63, 20));
        label_31 = new QLabel(tab_6);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(270, 410, 63, 20));
        label_32 = new QLabel(tab_6);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(270, 360, 63, 20));
        label_33 = new QLabel(tab_6);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(30, 560, 51, 20));
        lnECmd2 = new QLineEdit(tab_6);
        lnECmd2->setObjectName(QString::fromUtf8("lnECmd2"));
        lnECmd2->setGeometry(QRect(110, 670, 381, 26));
        lnERecv_theta3_2 = new QLineEdit(tab_6);
        lnERecv_theta3_2->setObjectName(QString::fromUtf8("lnERecv_theta3_2"));
        lnERecv_theta3_2->setGeometry(QRect(350, 450, 111, 31));
        lnERecv_roll2 = new QLineEdit(tab_6);
        lnERecv_roll2->setObjectName(QString::fromUtf8("lnERecv_roll2"));
        lnERecv_roll2->setGeometry(QRect(110, 510, 113, 26));
        lnERecv_x2 = new QLineEdit(tab_6);
        lnERecv_x2->setObjectName(QString::fromUtf8("lnERecv_x2"));
        lnERecv_x2->setGeometry(QRect(110, 360, 113, 26));
        lnERecv_pitch2 = new QLineEdit(tab_6);
        lnERecv_pitch2->setObjectName(QString::fromUtf8("lnERecv_pitch2"));
        lnERecv_pitch2->setGeometry(QRect(110, 560, 113, 26));
        lnERecv_theta1_2 = new QLineEdit(tab_6);
        lnERecv_theta1_2->setObjectName(QString::fromUtf8("lnERecv_theta1_2"));
        lnERecv_theta1_2->setGeometry(QRect(350, 350, 111, 31));
        label_34 = new QLabel(tab_6);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(270, 460, 63, 20));
        label_35 = new QLabel(tab_6);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(30, 460, 31, 20));
        label_36 = new QLabel(tab_6);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(30, 360, 31, 20));
        lnERecv_z2 = new QLineEdit(tab_6);
        lnERecv_z2->setObjectName(QString::fromUtf8("lnERecv_z2"));
        lnERecv_z2->setGeometry(QRect(110, 460, 113, 26));
        label_37 = new QLabel(tab_6);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(30, 510, 41, 20));
        label_38 = new QLabel(tab_6);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(30, 410, 21, 20));
        groupBox_7 = new QGroupBox(tab_6);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(20, 10, 451, 311));
        groupBox_7->setAlignment(Qt::AlignCenter);
        label_54 = new QLabel(groupBox_7);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(10, 30, 101, 20));
        label_55 = new QLabel(groupBox_7);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 70, 111, 20));
        label_56 = new QLabel(groupBox_7);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(10, 180, 101, 20));
        label_57 = new QLabel(groupBox_7);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(10, 140, 101, 20));
        label_58 = new QLabel(groupBox_7);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(10, 110, 201, 20));
        lnE_ToolNum3 = new QLineEdit(groupBox_7);
        lnE_ToolNum3->setObjectName(QString::fromUtf8("lnE_ToolNum3"));
        lnE_ToolNum3->setGeometry(QRect(130, 30, 113, 26));
        lnE_JogSp3 = new QLineEdit(groupBox_7);
        lnE_JogSp3->setObjectName(QString::fromUtf8("lnE_JogSp3"));
        lnE_JogSp3->setGeometry(QRect(130, 70, 211, 26));
        lnE_Coord3 = new QLineEdit(groupBox_7);
        lnE_Coord3->setObjectName(QString::fromUtf8("lnE_Coord3"));
        lnE_Coord3->setGeometry(QRect(220, 100, 211, 26));
        lnE_ServoStt3 = new QLineEdit(groupBox_7);
        lnE_ServoStt3->setObjectName(QString::fromUtf8("lnE_ServoStt3"));
        lnE_ServoStt3->setGeometry(QRect(130, 140, 211, 26));
        lnE_SysStt3 = new QLineEdit(groupBox_7);
        lnE_SysStt3->setObjectName(QString::fromUtf8("lnE_SysStt3"));
        lnE_SysStt3->setGeometry(QRect(130, 180, 211, 26));
        label_68 = new QLabel(groupBox_7);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(10, 260, 101, 20));
        label_69 = new QLabel(groupBox_7);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(10, 220, 63, 20));
        lnE_SysStt1_6 = new QLineEdit(groupBox_7);
        lnE_SysStt1_6->setObjectName(QString::fromUtf8("lnE_SysStt1_6"));
        lnE_SysStt1_6->setGeometry(QRect(130, 260, 211, 26));
        lnE_SysStt1_7 = new QLineEdit(groupBox_7);
        lnE_SysStt1_7->setObjectName(QString::fromUtf8("lnE_SysStt1_7"));
        lnE_SysStt1_7->setGeometry(QRect(130, 220, 211, 26));
        tabWidget_2->addTab(tab_6, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        label_92 = new QLabel(tab_5);
        label_92->setObjectName(QString::fromUtf8("label_92"));
        label_92->setGeometry(QRect(30, 500, 41, 20));
        lnERecv_y3 = new QLineEdit(tab_5);
        lnERecv_y3->setObjectName(QString::fromUtf8("lnERecv_y3"));
        lnERecv_y3->setGeometry(QRect(110, 400, 113, 26));
        label_93 = new QLabel(tab_5);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(30, 400, 21, 20));
        label_94 = new QLabel(tab_5);
        label_94->setObjectName(QString::fromUtf8("label_94"));
        label_94->setGeometry(QRect(30, 350, 31, 20));
        lnERecv_roll3 = new QLineEdit(tab_5);
        lnERecv_roll3->setObjectName(QString::fromUtf8("lnERecv_roll3"));
        lnERecv_roll3->setGeometry(QRect(110, 500, 113, 26));
        label_95 = new QLabel(tab_5);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(30, 550, 51, 20));
        label_96 = new QLabel(tab_5);
        label_96->setObjectName(QString::fromUtf8("label_96"));
        label_96->setGeometry(QRect(20, 660, 81, 20));
        lnERecv_yaw3 = new QLineEdit(tab_5);
        lnERecv_yaw3->setObjectName(QString::fromUtf8("lnERecv_yaw3"));
        lnERecv_yaw3->setGeometry(QRect(110, 600, 113, 26));
        lnERecv_J4 = new QLineEdit(tab_5);
        lnERecv_J4->setObjectName(QString::fromUtf8("lnERecv_J4"));
        lnERecv_J4->setGeometry(QRect(370, 500, 111, 31));
        lnERecv_z3 = new QLineEdit(tab_5);
        lnERecv_z3->setObjectName(QString::fromUtf8("lnERecv_z3"));
        lnERecv_z3->setGeometry(QRect(110, 450, 113, 26));
        lnERecv_pitch3 = new QLineEdit(tab_5);
        lnERecv_pitch3->setObjectName(QString::fromUtf8("lnERecv_pitch3"));
        lnERecv_pitch3->setGeometry(QRect(110, 550, 113, 26));
        label_97 = new QLabel(tab_5);
        label_97->setObjectName(QString::fromUtf8("label_97"));
        label_97->setGeometry(QRect(30, 600, 63, 20));
        lnERecv_J1 = new QLineEdit(tab_5);
        lnERecv_J1->setObjectName(QString::fromUtf8("lnERecv_J1"));
        lnERecv_J1->setGeometry(QRect(370, 350, 111, 31));
        lnERecv_J3 = new QLineEdit(tab_5);
        lnERecv_J3->setObjectName(QString::fromUtf8("lnERecv_J3"));
        lnERecv_J3->setGeometry(QRect(370, 450, 111, 31));
        label_98 = new QLabel(tab_5);
        label_98->setObjectName(QString::fromUtf8("label_98"));
        label_98->setGeometry(QRect(30, 450, 31, 20));
        lnERecv_J2 = new QLineEdit(tab_5);
        lnERecv_J2->setObjectName(QString::fromUtf8("lnERecv_J2"));
        lnERecv_J2->setGeometry(QRect(370, 400, 111, 31));
        lnECmd3 = new QLineEdit(tab_5);
        lnECmd3->setObjectName(QString::fromUtf8("lnECmd3"));
        lnECmd3->setGeometry(QRect(110, 660, 381, 26));
        lnERecv_x3 = new QLineEdit(tab_5);
        lnERecv_x3->setObjectName(QString::fromUtf8("lnERecv_x3"));
        lnERecv_x3->setGeometry(QRect(110, 350, 113, 26));
        label_99 = new QLabel(tab_5);
        label_99->setObjectName(QString::fromUtf8("label_99"));
        label_99->setGeometry(QRect(290, 360, 63, 20));
        label_100 = new QLabel(tab_5);
        label_100->setObjectName(QString::fromUtf8("label_100"));
        label_100->setGeometry(QRect(290, 410, 63, 20));
        label_101 = new QLabel(tab_5);
        label_101->setObjectName(QString::fromUtf8("label_101"));
        label_101->setGeometry(QRect(290, 460, 63, 20));
        label_102 = new QLabel(tab_5);
        label_102->setObjectName(QString::fromUtf8("label_102"));
        label_102->setGeometry(QRect(290, 510, 63, 20));
        lnERecv_J5 = new QLineEdit(tab_5);
        lnERecv_J5->setObjectName(QString::fromUtf8("lnERecv_J5"));
        lnERecv_J5->setGeometry(QRect(370, 550, 111, 31));
        label_103 = new QLabel(tab_5);
        label_103->setObjectName(QString::fromUtf8("label_103"));
        label_103->setGeometry(QRect(290, 560, 63, 20));
        lnERecv_J6 = new QLineEdit(tab_5);
        lnERecv_J6->setObjectName(QString::fromUtf8("lnERecv_J6"));
        lnERecv_J6->setGeometry(QRect(370, 600, 111, 31));
        label_104 = new QLabel(tab_5);
        label_104->setObjectName(QString::fromUtf8("label_104"));
        label_104->setGeometry(QRect(290, 610, 63, 20));
        groupBox_8 = new QGroupBox(tab_5);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(20, 10, 451, 301));
        groupBox_8->setAlignment(Qt::AlignCenter);
        label_59 = new QLabel(groupBox_8);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(10, 30, 101, 20));
        label_60 = new QLabel(groupBox_8);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(10, 70, 111, 20));
        label_61 = new QLabel(groupBox_8);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(10, 180, 101, 20));
        label_62 = new QLabel(groupBox_8);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(10, 140, 101, 20));
        label_63 = new QLabel(groupBox_8);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(10, 110, 201, 20));
        lnE_ToolNum4 = new QLineEdit(groupBox_8);
        lnE_ToolNum4->setObjectName(QString::fromUtf8("lnE_ToolNum4"));
        lnE_ToolNum4->setGeometry(QRect(130, 30, 113, 26));
        lnE_JogSp4 = new QLineEdit(groupBox_8);
        lnE_JogSp4->setObjectName(QString::fromUtf8("lnE_JogSp4"));
        lnE_JogSp4->setGeometry(QRect(130, 70, 211, 26));
        lnE_Coord = new QLineEdit(groupBox_8);
        lnE_Coord->setObjectName(QString::fromUtf8("lnE_Coord"));
        lnE_Coord->setGeometry(QRect(220, 100, 211, 26));
        lnE_ServoStt4 = new QLineEdit(groupBox_8);
        lnE_ServoStt4->setObjectName(QString::fromUtf8("lnE_ServoStt4"));
        lnE_ServoStt4->setGeometry(QRect(130, 140, 211, 26));
        lnE_SysStt4 = new QLineEdit(groupBox_8);
        lnE_SysStt4->setObjectName(QString::fromUtf8("lnE_SysStt4"));
        lnE_SysStt4->setGeometry(QRect(130, 180, 211, 26));
        label_70 = new QLabel(groupBox_8);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(10, 260, 101, 20));
        label_71 = new QLabel(groupBox_8);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(10, 220, 63, 20));
        lnE_SysStt1_8 = new QLineEdit(groupBox_8);
        lnE_SysStt1_8->setObjectName(QString::fromUtf8("lnE_SysStt1_8"));
        lnE_SysStt1_8->setGeometry(QRect(130, 260, 211, 26));
        lnE_SysStt1_9 = new QLineEdit(groupBox_8);
        lnE_SysStt1_9->setObjectName(QString::fromUtf8("lnE_SysStt1_9"));
        lnE_SysStt1_9->setGeometry(QRect(130, 220, 211, 26));
        tabWidget_2->addTab(tab_5, QString());
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(500, 20, 81, 20));
        lnETime = new QLineEdit(centralwidget);
        lnETime->setObjectName(QString::fromUtf8("lnETime"));
        lnETime->setGeometry(QRect(610, 20, 151, 26));
        btnStop = new QPushButton(centralwidget);
        btnStop->setObjectName(QString::fromUtf8("btnStop"));
        btnStop->setGeometry(QRect(860, 60, 93, 29));
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(1040, 30, 121, 20));
        lnENoclients = new QLineEdit(centralwidget);
        lnENoclients->setObjectName(QString::fromUtf8("lnENoclients"));
        lnENoclients->setGeometry(QRect(1170, 20, 113, 26));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1581, 26));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);
        tabWidget_3->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        lbSttMsg->setText(QCoreApplication::translate("MainWindow", "Connection Status Message", nullptr));
        btnStart->setText(QCoreApplication::translate("MainWindow", "Start", nullptr));
        groupBox->setTitle(QCoreApplication::translate("MainWindow", "Robot Command", nullptr));
        btnSVOFF->setText(QCoreApplication::translate("MainWindow", "SERVO OFF", nullptr));
        btnSVON->setText(QCoreApplication::translate("MainWindow", "SERVO ON", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("MainWindow", "Speed", nullptr));
        btnSpeed_low->setText(QCoreApplication::translate("MainWindow", "LOW", nullptr));
        btnSpeed_med->setText(QCoreApplication::translate("MainWindow", "MEDIUM", nullptr));
        btnSpeed_high->setText(QCoreApplication::translate("MainWindow", "HIGH", nullptr));
        btnSpeed_top->setText(QCoreApplication::translate("MainWindow", "TOP", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("MainWindow", "Jog", nullptr));
        btnJ2_neg->setText(QCoreApplication::translate("MainWindow", "J2-", nullptr));
        btnJ4_neg->setText(QCoreApplication::translate("MainWindow", "J4-", nullptr));
        btnJ3_neg->setText(QCoreApplication::translate("MainWindow", "J3-", nullptr));
        btnJ1_pos->setText(QCoreApplication::translate("MainWindow", "J1+", nullptr));
        btnJ1_neg->setText(QCoreApplication::translate("MainWindow", "J1- ", nullptr));
        btnJ2_pos->setText(QCoreApplication::translate("MainWindow", "J2+", nullptr));
        btnJ3_pos->setText(QCoreApplication::translate("MainWindow", "J3+", nullptr));
        btnJ4_pos->setText(QCoreApplication::translate("MainWindow", "J4+", nullptr));
        btnJ5_pos->setText(QCoreApplication::translate("MainWindow", "J5+", nullptr));
        btnJ5_neg->setText(QCoreApplication::translate("MainWindow", "J5-", nullptr));
        btnJ6_pos->setText(QCoreApplication::translate("MainWindow", "J6+", nullptr));
        btnJ6_neg->setText(QCoreApplication::translate("MainWindow", "J6-", nullptr));
        chbCoords->setItemText(0, QCoreApplication::translate("MainWindow", "Choose Coordinates", nullptr));
        chbCoords->setItemText(1, QCoreApplication::translate("MainWindow", "Joint Coordinates", nullptr));
        chbCoords->setItemText(2, QCoreApplication::translate("MainWindow", "Cartesian Coordinates", nullptr));
        chbCoords->setItemText(3, QCoreApplication::translate("MainWindow", "Tool Coordinates", nullptr));
        chbCoords->setItemText(4, QCoreApplication::translate("MainWindow", "User Coordinates", nullptr));

        chbTools->setItemText(0, QCoreApplication::translate("MainWindow", "#0: Standard Tool", nullptr));

        label_42->setText(QCoreApplication::translate("MainWindow", "Coordinate", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "Tool", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindow", "JOG", nullptr));
        btnSendProg->setText(QCoreApplication::translate("MainWindow", "Send Program", nullptr));
        btnWriteProg->setText(QCoreApplication::translate("MainWindow", "Write a Program", nullptr));
        btnCompProg->setText(QCoreApplication::translate("MainWindow", "Compile Program", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Name of program", nullptr));
        btnSendPoints->setText(QCoreApplication::translate("MainWindow", "Send Taught Points", nullptr));
        btnChPoints->setText(QCoreApplication::translate("MainWindow", "Choose Taught Points", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("MainWindow", "PROGRAM", nullptr));
        btnDataAdd->setText(QCoreApplication::translate("MainWindow", "Add", nullptr));
        btnDataReteach->setText(QCoreApplication::translate("MainWindow", "Re-teach", nullptr));
        btnDataMove->setText(QCoreApplication::translate("MainWindow", "Move", nullptr));
        btnDataDel->setText(QCoreApplication::translate("MainWindow", "Delete", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tabJPointList_1->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("MainWindow", "P", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tabJPointList_1->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("MainWindow", "J1", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tabJPointList_1->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("MainWindow", "J2", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tabJPointList_1->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("MainWindow", "J3", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tabJPointList_1->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("MainWindow", "J4", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tabJPointList_1->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("MainWindow", "J5", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tabJPointList_1->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("MainWindow", "J6", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tabJPointList_2->horizontalHeaderItem(0);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("MainWindow", "P", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tabJPointList_2->horizontalHeaderItem(1);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("MainWindow", "J1", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tabJPointList_2->horizontalHeaderItem(2);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("MainWindow", "J2", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tabJPointList_2->horizontalHeaderItem(3);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("MainWindow", "J3", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tabJPointList_2->horizontalHeaderItem(4);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("MainWindow", "J4", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tabJPointList_2->horizontalHeaderItem(5);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("MainWindow", "J5", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tabJPointList_2->horizontalHeaderItem(6);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("MainWindow", "J6", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tabJPointList_3->horizontalHeaderItem(0);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("MainWindow", "P", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tabJPointList_3->horizontalHeaderItem(1);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("MainWindow", "J1", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tabJPointList_3->horizontalHeaderItem(2);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("MainWindow", "J2", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tabJPointList_3->horizontalHeaderItem(3);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("MainWindow", "J3", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tabJPointList_3->horizontalHeaderItem(4);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("MainWindow", "J4", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tabJPointList_3->horizontalHeaderItem(5);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("MainWindow", "J5", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tabJPointList_3->horizontalHeaderItem(6);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("MainWindow", "J6", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tabJPointList_4->horizontalHeaderItem(0);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("MainWindow", "P", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tabJPointList_4->horizontalHeaderItem(1);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("MainWindow", "J1", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tabJPointList_4->horizontalHeaderItem(2);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("MainWindow", "J2", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = tabJPointList_4->horizontalHeaderItem(3);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("MainWindow", "J3", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tabJPointList_4->horizontalHeaderItem(4);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("MainWindow", "J4", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tabJPointList_4->horizontalHeaderItem(5);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("MainWindow", "J5", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = tabJPointList_4->horizontalHeaderItem(6);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("MainWindow", "J6", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_8), QCoreApplication::translate("MainWindow", "Joint Point List", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = tabWPointList_1->horizontalHeaderItem(0);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("MainWindow", "P", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = tabWPointList_1->horizontalHeaderItem(1);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = tabWPointList_1->horizontalHeaderItem(2);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = tabWPointList_1->horizontalHeaderItem(3);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem32 = tabWPointList_1->horizontalHeaderItem(4);
        ___qtablewidgetitem32->setText(QCoreApplication::translate("MainWindow", "Rx", nullptr));
        QTableWidgetItem *___qtablewidgetitem33 = tabWPointList_1->horizontalHeaderItem(5);
        ___qtablewidgetitem33->setText(QCoreApplication::translate("MainWindow", "Ry", nullptr));
        QTableWidgetItem *___qtablewidgetitem34 = tabWPointList_1->horizontalHeaderItem(6);
        ___qtablewidgetitem34->setText(QCoreApplication::translate("MainWindow", "Rz", nullptr));
        QTableWidgetItem *___qtablewidgetitem35 = tabWPointList_2->horizontalHeaderItem(0);
        ___qtablewidgetitem35->setText(QCoreApplication::translate("MainWindow", "P", nullptr));
        QTableWidgetItem *___qtablewidgetitem36 = tabWPointList_2->horizontalHeaderItem(1);
        ___qtablewidgetitem36->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem37 = tabWPointList_2->horizontalHeaderItem(2);
        ___qtablewidgetitem37->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem38 = tabWPointList_2->horizontalHeaderItem(3);
        ___qtablewidgetitem38->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem39 = tabWPointList_2->horizontalHeaderItem(4);
        ___qtablewidgetitem39->setText(QCoreApplication::translate("MainWindow", "Rx", nullptr));
        QTableWidgetItem *___qtablewidgetitem40 = tabWPointList_2->horizontalHeaderItem(5);
        ___qtablewidgetitem40->setText(QCoreApplication::translate("MainWindow", "Ry", nullptr));
        QTableWidgetItem *___qtablewidgetitem41 = tabWPointList_2->horizontalHeaderItem(6);
        ___qtablewidgetitem41->setText(QCoreApplication::translate("MainWindow", "Rz", nullptr));
        QTableWidgetItem *___qtablewidgetitem42 = tabWPointList_3->horizontalHeaderItem(0);
        ___qtablewidgetitem42->setText(QCoreApplication::translate("MainWindow", "P", nullptr));
        QTableWidgetItem *___qtablewidgetitem43 = tabWPointList_3->horizontalHeaderItem(1);
        ___qtablewidgetitem43->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem44 = tabWPointList_3->horizontalHeaderItem(2);
        ___qtablewidgetitem44->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem45 = tabWPointList_3->horizontalHeaderItem(3);
        ___qtablewidgetitem45->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem46 = tabWPointList_3->horizontalHeaderItem(4);
        ___qtablewidgetitem46->setText(QCoreApplication::translate("MainWindow", "Rx", nullptr));
        QTableWidgetItem *___qtablewidgetitem47 = tabWPointList_3->horizontalHeaderItem(5);
        ___qtablewidgetitem47->setText(QCoreApplication::translate("MainWindow", "Ry", nullptr));
        QTableWidgetItem *___qtablewidgetitem48 = tabWPointList_3->horizontalHeaderItem(6);
        ___qtablewidgetitem48->setText(QCoreApplication::translate("MainWindow", "Rz", nullptr));
        QTableWidgetItem *___qtablewidgetitem49 = tabWPointList_4->horizontalHeaderItem(0);
        ___qtablewidgetitem49->setText(QCoreApplication::translate("MainWindow", "P", nullptr));
        QTableWidgetItem *___qtablewidgetitem50 = tabWPointList_4->horizontalHeaderItem(1);
        ___qtablewidgetitem50->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem51 = tabWPointList_4->horizontalHeaderItem(2);
        ___qtablewidgetitem51->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem52 = tabWPointList_4->horizontalHeaderItem(3);
        ___qtablewidgetitem52->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem53 = tabWPointList_4->horizontalHeaderItem(4);
        ___qtablewidgetitem53->setText(QCoreApplication::translate("MainWindow", "Rx", nullptr));
        QTableWidgetItem *___qtablewidgetitem54 = tabWPointList_4->horizontalHeaderItem(5);
        ___qtablewidgetitem54->setText(QCoreApplication::translate("MainWindow", "Ry", nullptr));
        QTableWidgetItem *___qtablewidgetitem55 = tabWPointList_4->horizontalHeaderItem(6);
        ___qtablewidgetitem55->setText(QCoreApplication::translate("MainWindow", "Rz", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_9), QCoreApplication::translate("MainWindow", "World Point List", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_7), QCoreApplication::translate("MainWindow", "DATA", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Robot", nullptr));
        comboBox->setItemText(0, QCoreApplication::translate("MainWindow", "Choose Robot", nullptr));
        comboBox->setItemText(1, QCoreApplication::translate("MainWindow", "SCARA", nullptr));
        comboBox->setItemText(2, QCoreApplication::translate("MainWindow", "DELTA1", nullptr));
        comboBox->setItemText(3, QCoreApplication::translate("MainWindow", "MANIPULATOR", nullptr));

        groupBox_2->setTitle(QCoreApplication::translate("MainWindow", "Robot Data Acquisition", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "roll", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "d3", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "y", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "theta1", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "yaw", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "theta2", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "x ", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "theta4", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "z", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "pitch", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Command", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("MainWindow", "Status", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Tool Number", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Jogging Speed", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "System Status", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "Servo Status", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "Operation Coordinate System", nullptr));
        label_64->setText(QCoreApplication::translate("MainWindow", "Mode", nullptr));
        label_65->setText(QCoreApplication::translate("MainWindow", "Security Level", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_3), QCoreApplication::translate("MainWindow", "SCARA", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "x ", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "theta1", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "pitch", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "roll", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "yaw", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "theta3", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "y", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "Command", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "z", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "theta2", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("MainWindow", "Status", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "Tool Number", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindow", "Jogging Speed", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "System Status", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindow", "Servo Status", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindow", "Operation Coordinate System", nullptr));
        label_66->setText(QCoreApplication::translate("MainWindow", "Security Level", nullptr));
        label_67->setText(QCoreApplication::translate("MainWindow", "Mode", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QCoreApplication::translate("MainWindow", "DELTA 1", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "Command", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "yaw", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "theta2", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "theta1", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "pitch", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "theta3", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "z", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "x ", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "roll", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "y", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("MainWindow", "Status", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindow", "Tool Number", nullptr));
        label_55->setText(QCoreApplication::translate("MainWindow", "Jogging Speed", nullptr));
        label_56->setText(QCoreApplication::translate("MainWindow", "System Status", nullptr));
        label_57->setText(QCoreApplication::translate("MainWindow", "Servo Status", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindow", "Operation Coordinate System", nullptr));
        label_68->setText(QCoreApplication::translate("MainWindow", "Security Level", nullptr));
        label_69->setText(QCoreApplication::translate("MainWindow", "Mode", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_6), QCoreApplication::translate("MainWindow", "DELTA 2", nullptr));
        label_92->setText(QCoreApplication::translate("MainWindow", "roll", nullptr));
        label_93->setText(QCoreApplication::translate("MainWindow", "y", nullptr));
        label_94->setText(QCoreApplication::translate("MainWindow", "x ", nullptr));
        label_95->setText(QCoreApplication::translate("MainWindow", "pitch", nullptr));
        label_96->setText(QCoreApplication::translate("MainWindow", "Command", nullptr));
        label_97->setText(QCoreApplication::translate("MainWindow", "yaw", nullptr));
        label_98->setText(QCoreApplication::translate("MainWindow", "z", nullptr));
        label_99->setText(QCoreApplication::translate("MainWindow", "joint 1", nullptr));
        label_100->setText(QCoreApplication::translate("MainWindow", "joint 2", nullptr));
        label_101->setText(QCoreApplication::translate("MainWindow", "joint 3", nullptr));
        label_102->setText(QCoreApplication::translate("MainWindow", "joint 4", nullptr));
        label_103->setText(QCoreApplication::translate("MainWindow", "joint 5", nullptr));
        label_104->setText(QCoreApplication::translate("MainWindow", "joint 6", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("MainWindow", "Status", nullptr));
        label_59->setText(QCoreApplication::translate("MainWindow", "Tool Number", nullptr));
        label_60->setText(QCoreApplication::translate("MainWindow", "Jogging Speed", nullptr));
        label_61->setText(QCoreApplication::translate("MainWindow", "System Status", nullptr));
        label_62->setText(QCoreApplication::translate("MainWindow", "Servo Status", nullptr));
        label_63->setText(QCoreApplication::translate("MainWindow", "Operation Coordinate System", nullptr));
        label_70->setText(QCoreApplication::translate("MainWindow", "Security Level", nullptr));
        label_71->setText(QCoreApplication::translate("MainWindow", "Mode", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QCoreApplication::translate("MainWindow", "MANIPULATOR", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "TimeStamp", nullptr));
        btnStop->setText(QCoreApplication::translate("MainWindow", "Stop", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Number of clients", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
